### ISSUE TITLE
Data::Section doesn't work when used in a role

### ISSUE THREAD

**Issue by autarch** [rjbs/Data-Section#13]
I forked the repo to try and fix this but it's not that easy.

My first thought was that we could simply capture the package name into which Data::Section exports its methods and use that instead of looking at `$self`.

However, the `merged_section_data` method relies on looking at the isa chain for `$self`, which basically excludes roles entirely.

I'll probably come up some sort of hack for my own code, but I'm not sure how to fix this, or even if it's possible to do so without simply implementing this whole thing as a Moo(se)? role itself.

**Comment by rjbs** [comment]
I'm not sure.  I think the whole would want to be re-implemented with something like MooseX::ComposedBehavior.
